version: "3"

services:
  abibliadigital:
    build: ./docker-api
    command: ["bash", "/usr/src/api/start.sh"]
    ports:
      - "6000:6000"
    expose:
      - "6000"
    container_name: abibliadigital
    environment:
      - PORT=6000
      - MONGODB_URI=mongodb://abibliadigital-mongo/abibliadigital
      - NODE_ENV=production
      - SECRET_KEY=19B2AFFC3B287A4E41FA7C1158A8A
      - REDIS_URL=redis://abibliadigital-redis
    volumes:
      - ../abibliadigital:/usr/src/api
    depends_on:
      - abibliadigital-mongo
      - abibliadigital-redis

  abibliadigital-mongo:
    build: ./docker-mongo
    container_name: abibliadigital-mongo
    ports:
      - "27117:27117"
    expose:
      - "27117"
    volumes:
      - ../mongo-abibliadigital/db/data:/data/db
      - ../mongo-abibliadigital/db/log:/var/log/mongodb

  abibliadigital-redis:
    image: "redis:alpine"
    container_name: abibliadigital-redis
    command: redis-server
    ports:
      - "8479:8479"
    expose:
      - "8479"
    restart: always
    volumes:
      - ../redis-data:/var/lib/redis
